#!/bin/bash
#Autor: @joseccnet
version="1.0"
timedate=$(date +%Y%m%d-%H%M%S)

if [ "$1" != "AGREE" ] ; then

echo -e "
DebAPoint $version - @joseccnet

****A T E N C I O N****

DebAPoint esta disen~ado para ejecutarse sobre una instalacion NUEVA/FRESCA de Debian *7(Wheezy)* o Debian *8(Jessie)*. Ponga atencion a esta nota, ya que este script MODIFICARA dos archivos importantes del sistema: /etc/apt/sources.list y /etc/network/interfaces

Si ustede esta de acuerdo, ejecute este comando de la siguiente manera:

   $0 AGREE"
exit -1
fi

if [ -f /var/tmp/.runonce ] ; then
    echo "Este script ya se ejecuto. Considere ejecutarlo en una instalacion nueva."
    exit -1
else
    touch /var/tmp/.runonce
fi

mkdir -p /opt/ap/ > /dev/null 2>&1

etcaptsourceslistdeb7="IyAKCiMgZGViIGNkcm9tOltEZWJpYW4gR05VL0xpbnV4IDcuOC4wIF9XaGVlenlfIC0gT2ZmaWNpYWwgYW1kNjQgTkVUSU5TVCBCaW5hcnktMSAyMDE1MDExMC0xNDo0MV0vIHdoZWV6eSBtYWluCgojZGViIGNkcm9tOltEZWJpYW4gR05VL0xpbnV4IDcuOC4wIF9XaGVlenlfIC0gT2ZmaWNpYWwgYW1kNjQgTkVUSU5TVCBCaW5hcnktMSAyMDE1MDExMC0xNDo0MV0vIHdoZWV6eSBtYWluCgpkZWIgaHR0cDovL2Nkbi5kZWJpYW4ubmV0L2RlYmlhbi8gd2hlZXp5IG1haW4gbm9uLWZyZWUKZGViLXNyYyBodHRwOi8vY2RuLmRlYmlhbi5uZXQvZGViaWFuLyB3aGVlenkgbWFpbiBub24tZnJlZQoKZGViIGh0dHA6Ly9zZWN1cml0eS5kZWJpYW4ub3JnLyB3aGVlenkvdXBkYXRlcyBtYWluIG5vbi1mcmVlCmRlYi1zcmMgaHR0cDovL3NlY3VyaXR5LmRlYmlhbi5vcmcvIHdoZWV6eS91cGRhdGVzIG1haW4gbm9uLWZyZWUKCiMgd2hlZXp5LXVwZGF0ZXMsIHByZXZpb3VzbHkga25vd24gYXMgJ3ZvbGF0aWxlJwpkZWIgaHR0cDovL2Nkbi5kZWJpYW4ubmV0L2RlYmlhbi8gd2hlZXp5LXVwZGF0ZXMgbWFpbiBub24tZnJlZQpkZWItc3JjIGh0dHA6Ly9jZG4uZGViaWFuLm5ldC9kZWJpYW4vIHdoZWV6eS11cGRhdGVzIG1haW4gbm9uLWZyZWUKCiNQYXJhIERlYkFjY2Vzc1BvaW50OgpkZWIgaHR0cDovL2h0dHAuZGViaWFuLm5ldC9kZWJpYW4gd2hlZXp5LWJhY2twb3J0cyBtYWluIG5vbi1mcmVlCg=="

etcaptsourceslistdeb8="IyAKCiMgZGViIGNkcm9tOltEZWJpYW4gR05VL0xpbnV4IDguMS4wIF9KZXNzaWVfIC0gT2ZmaWNpYWwgYW1kNjQgTkVUSU5TVCBCaW5hcnktMSAyMDE1MDYwNi0xNDoxNl0vIGplc3NpZSBtYWluCgojZGViIGNkcm9tOltEZWJpYW4gR05VL0xpbnV4IDguMS4wIF9KZXNzaWVfIC0gT2ZmaWNpYWwgYW1kNjQgTkVUSU5TVCBCaW5hcnktMSAyMDE1MDYwNi0xNDoxNl0vIGplc3NpZSBtYWluCgpkZWIgaHR0cDovL2h0dHByZWRpci5kZWJpYW4ub3JnL2RlYmlhbi8gamVzc2llIG1haW4gbm9uLWZyZWUKZGViLXNyYyBodHRwOi8vaHR0cHJlZGlyLmRlYmlhbi5vcmcvZGViaWFuLyBqZXNzaWUgbWFpbiBub24tZnJlZQoKZGViIGh0dHA6Ly9zZWN1cml0eS5kZWJpYW4ub3JnLyBqZXNzaWUvdXBkYXRlcyBtYWluIG5vbi1mcmVlCmRlYi1zcmMgaHR0cDovL3NlY3VyaXR5LmRlYmlhbi5vcmcvIGplc3NpZS91cGRhdGVzIG1haW4gbm9uLWZyZWUKCiMgamVzc2llLXVwZGF0ZXMsIHByZXZpb3VzbHkga25vd24gYXMgJ3ZvbGF0aWxlJwpkZWIgaHR0cDovL2h0dHByZWRpci5kZWJpYW4ub3JnL2RlYmlhbi8gamVzc2llLXVwZGF0ZXMgbWFpbiBub24tZnJlZQpkZWItc3JjIGh0dHA6Ly9odHRwcmVkaXIuZGViaWFuLm9yZy9kZWJpYW4vIGplc3NpZS11cGRhdGVzIG1haW4gbm9uLWZyZWUK"

etcnetworkinterfacesBridge="IyBUaGlzIGZpbGUgZGVzY3JpYmVzIHRoZSBuZXR3b3JrIGludGVyZmFjZXMgYXZhaWxhYmxlIG9uIHlvdXIgc3lzdGVtCiMgYW5kIGhvdyB0byBhY3RpdmF0ZSB0aGVtLiBGb3IgbW9yZSBpbmZvcm1hdGlvbiwgc2VlIGludGVyZmFjZXMoNSkuCgojIFRoZSBsb29wYmFjayBuZXR3b3JrIGludGVyZmFjZQphdXRvIGxvIGJyMAppZmFjZSBsbyBpbmV0IGxvb3BiYWNrCgphbGxvdy1ob3RwbHVnIGV0aDAKaWZhY2UgZXRoMCBpbmV0IG1hbnVhbAoKYWxsb3ctaG90cGx1ZyB3bGFuMAppZmFjZSB3bGFuMCBpbmV0IG1hbnVhbApwcmUtdXAgL29wdC9hcC9hcC5zaCBNb2RlQnJpZGdlICRJRkFDRSAxLjEuMSBBUC1OYW1lLSRJRkFDRSAxMTMzNTU3Nzk5ID4+IC9vcHQvYXAvYXAuc2gubG9nIDI+JjEKCmFsbG93LWhvdHBsdWcgd2xhbjEKaWZhY2Ugd2xhbjEgaW5ldCBtYW51YWwKcHJlLXVwIC9vcHQvYXAvYXAuc2ggTW9kZUJyaWRnZSAkSUZBQ0UgMS4xLjEgQVAtTmFtZS0kSUZBQ0UgMTEzMzU1Nzc5OSA+PiAvb3B0L2FwL2FwLnNoLmxvZyAyPiYxCgphbGxvdy1ob3RwbHVnIHdsYW4yCmlmYWNlIHdsYW4yIGluZXQgbWFudWFsCnByZS11cCAvb3B0L2FwL2FwLnNoIE1vZGVCcmlkZ2UgJElGQUNFIDEuMS4xIEFQLU5hbWUtJElGQUNFIDExMzM1NTc3OTkgPj4gL29wdC9hcC9hcC5zaC5sb2cgMj4mMQoKYWxsb3ctaG90cGx1ZyB3bGFuMwppZmFjZSB3bGFuMiBpbmV0IG1hbnVhbApwcmUtdXAgL29wdC9hcC9hcC5zaCBNb2RlQnJpZGdlICRJRkFDRSAxLjEuMSBBUC1OYW1lLSRJRkFDRSAxMTMzNTU3Nzk5ID4+IC9vcHQvYXAvYXAuc2gubG9nIDI+JjEKCmFsbG93LWhvdHBsdWcgd2xhbjQKaWZhY2Ugd2xhbjIgaW5ldCBtYW51YWwKcHJlLXVwIC9vcHQvYXAvYXAuc2ggTW9kZUJyaWRnZSAkSUZBQ0UgMS4xLjEgQVAtTmFtZS0kSUZBQ0UgMTEzMzU1Nzc5OSA+PiAvb3B0L2FwL2FwLnNoLmxvZyAyPiYxCgppZmFjZSBicjAgaW5ldCBkaGNwCmJyaWRnZV9wb3J0cyBldGgwIHdsYW4wIHdsYW4xIHdsYW4yIHdsYW4zIHdsYW40CnVwIGVjaG8gMSA+IC9wcm9jL3N5cy9uZXQvaXB2NC9jb25mL2RlZmF1bHQvcnBfZmlsdGVyIDsgZWNobyAxID4gL3Byb2Mvc3lzL25ldC9pcHY0L2NvbmYvYWxsL2xvZ19tYXJ0aWFucyA7IGVjaG8gMSA+IC9wcm9jL3N5cy9uZXQvaXB2NC9pcF9keW5hZGRyCg=="

etcnetworkinterfacesNAT="IyBUaGlzIGZpbGUgZGVzY3JpYmVzIHRoZSBuZXR3b3JrIGludGVyZmFjZXMgYXZhaWxhYmxlIG9uIHlvdXIgc3lzdGVtCiMgYW5kIGhvdyB0byBhY3RpdmF0ZSB0aGVtLiBGb3IgbW9yZSBpbmZvcm1hdGlvbiwgc2VlIGludGVyZmFjZXMoNSkuCgpzb3VyY2UgL2V0Yy9uZXR3b3JrL2ludGVyZmFjZXMuZC8qCgojIFRoZSBsb29wYmFjayBuZXR3b3JrIGludGVyZmFjZQphdXRvIGxvCmlmYWNlIGxvIGluZXQgbG9vcGJhY2sKCiMgVGhlIHByaW1hcnkgbmV0d29yayBpbnRlcmZhY2UKYWxsb3ctaG90cGx1ZyBldGgwCmlmYWNlIGV0aDAgaW5ldCBkaGNwCnVwIGVjaG8gMSA+IC9wcm9jL3N5cy9uZXQvaXB2NC9jb25mL2FsbC9mb3J3YXJkaW5nCnVwIGVjaG8gMSA+IC9wcm9jL3N5cy9uZXQvaXB2Ni9jb25mL2FsbC9mb3J3YXJkaW5nCnVwIGlwdGFibGVzIC1GIDsgaXB0YWJsZXMgLUYgLXQgbmF0IDsgaXB0YWJsZXMgLUYgLXQgbmF0IDsgaXB0YWJsZXMgLVAgSU5QVVQgQUNDRVBUIDsgaXB0YWJsZXMgLVAgT1VUUFVUIEFDQ0VQVCA7IGlwdGFibGVzIC1QIEZPUldBUkQgQUNDRVBUIDsgaXB0YWJsZXMgLXQgbmF0IC1QIFBSRVJPVVRJTkcgQUNDRVBUIDsgaXB0YWJsZXMgLXQgbmF0IC1QIFBPU1RST1VUSU5HIEFDQ0VQVAp1cCBpcHRhYmxlcyAtdCBuYXQgLUEgUE9TVFJPVVRJTkcgLW8gZXRoKyAtaiBNQVNRVUVSQURFCnVwIGlwdGFibGVzIC1BIEZPUldBUkQgLWkgd2xhbisgLW8gZXRoKyAtaiBBQ0NFUFQKdXAgaXB0YWJsZXMgLUEgRk9SV0FSRCAtbSBjb25udHJhY2sgLS1jdHN0YXRlIE5FVyxSRUxBVEVELEVTVEFCTElTSEVEIC1qIEFDQ0VQVAp1cCBpcHRhYmxlcyAtQSBPVVRQVVQgLW0gY29ubnRyYWNrIC0tY3RzdGF0ZSBORVcsUkVMQVRFRCxFU1RBQkxJU0hFRCAtaiBBQ0NFUFQKCiNXaXJlbGVzcyBMQU5zOgoKYWxsb3ctaG90cGx1ZyB3bGFuMAppZmFjZSB3bGFuMCBpbmV0IG1hbnVhbApwcmUtdXAgaWZjb25maWcgJElGQUNFIDE5Mi4xNjguNTEuMSBuZXRtYXNrIDI1NS4yNTUuMjU1LjAgdXAgJiYgL29wdC9hcC9hcC5zaCBNb2RlTkFUICRJRkFDRSAxOTIuMTY4LjUxIEFQLU5hbWUtJElGQUNFIDExMzM1NTc3OTkgPj4gL29wdC9hcC9hcC5zaC5sb2cgMj4mMQoKYWxsb3ctaG90cGx1ZyB3bGFuMQppZmFjZSB3bGFuMSBpbmV0IG1hbnVhbApwcmUtdXAgaWZjb25maWcgJElGQUNFIDE5Mi4xNjguNjEuMSBuZXRtYXNrIDI1NS4yNTUuMjU1LjAgdXAgJiYgL29wdC9hcC9hcC5zaCBNb2RlTkFUICRJRkFDRSAxOTIuMTY4LjYxIEFQLU5hbWUtJElGQUNFIDExMzM1NTc3OTkgPj4gL29wdC9hcC9hcC5zaC5sb2cgMj4mMQoKYWxsb3ctaG90cGx1ZyB3bGFuMgppZmFjZSB3bGFuMiBpbmV0IG1hbnVhbApwcmUtdXAgaWZjb25maWcgJElGQUNFIDE5Mi4xNjguNzEuMSBuZXRtYXNrIDI1NS4yNTUuMjU1LjAgdXAgJiYgL29wdC9hcC9hcC5zaCBNb2RlTkFUICRJRkFDRSAxOTIuMTY4LjcxIEFQLU5hbWUtJElGQUNFIDExMzM1NTc3OTkgPj4gL29wdC9hcC9hcC5zaC5sb2cgMj4mMQoKYWxsb3ctaG90cGx1ZyB3bGFuMwppZmFjZSB3bGFuMyBpbmV0IG1hbnVhbApwcmUtdXAgaWZjb25maWcgJElGQUNFIDE5Mi4xNjguODEuMSBuZXRtYXNrIDI1NS4yNTUuMjU1LjAgdXAgJiYgL29wdC9hcC9hcC5zaCBNb2RlTkFUICRJRkFDRSAxOTIuMTY4LjgxIEFQLU5hbWUtJElGQUNFIDExMzM1NTc3OTkgPj4gL29wdC9hcC9hcC5zaC5sb2cgMj4mMQoKYWxsb3ctaG90cGx1ZyB3bGFuNAppZmFjZSB3bGFuNCBpbmV0IG1hbnVhbApwcmUtdXAgaWZjb25maWcgJElGQUNFIDE5Mi4xNjguOTEuMSBuZXRtYXNrIDI1NS4yNTUuMjU1LjAgdXAgJiYgL29wdC9hcC9hcC5zaCBNb2RlTkFUICRJRkFDRSAxOTIuMTY4LjkxIEFQLU5hbWUtJElGQUNFIDExMzM1NTc3OTkgPj4gL29wdC9hcC9hcC5zaC5sb2cgMj4mMQo="

hostapdconftemplate="aW50ZXJmYWNlPXdsYW5OCmRyaXZlcj1ubDgwMjExCgojIFlPVVIgQlJJREdFIE5BTUUKYnJpZGdlPWJyMAoKIyBZT1VSIENPVU5UUlkgSEVSRQpjb3VudHJ5X2NvZGU9VVMKaWVlZTgwMjExZD0xCgojIE1PRElGWSBZT1VSIFNTSUQgSEVSRQpzc2lkPU15T3duQVBSQU5ET00KCiMgQ0hBTkdFIE1PREUgSEVSRSBJRiBORUVERUQKaHdfbW9kZT1nCgojIENIQU5HRSBDSEFOTkVMIEVWRU5UVUFMTFkKY2hhbm5lbD03Cgp3bWVfZW5hYmxlZD0wCm1hY2FkZHJfYWNsPTAKYXV0aF9hbGdzPTEKCiMgSGlkZSBTU0lEOgojaWdub3JlX2Jyb2FkY2FzdF9zc2lkPTEKCiMgV0UgVVNFIFdQQTIKd3BhPTIKCiMgTU9ESUZZIFlPVVIgUEFTU1BIUkFTRSBIRVJFCndwYV9wYXNzcGhyYXNlPXBhc3N3b3JkQVAKCndwYV9rZXlfbWdtdD1XUEEtUFNLCndwYV9wYWlyd2lzZT1US0lQCnJzbl9wYWlyd2lzZT1DQ01QCgojIExldmVscyAobWluaW11bSB2YWx1ZSBmb3IgbG9nZ2VkIGV2ZW50cyk6CiMgIDAgPSB2ZXJib3NlIGRlYnVnZ2luZwojICAxID0gZGVidWdnaW5nCiMgIDIgPSBpbmZvcm1hdGlvbmFsIG1lc3NhZ2VzCiMgIDMgPSBub3RpZmljYXRpb24KIyAgNCA9IHdhcm5pbmcKIwpsb2dnZXJfc3lzbG9nPTAKbG9nZ2VyX3N5c2xvZ19sZXZlbD0xCmxvZ2dlcl9zdGRvdXQ9LTEKbG9nZ2VyX3N0ZG91dF9sZXZlbD0yCgptYXhfbnVtX3N0YT0yNTMKCiMgUHJldmVudCBkaXNzYXNvY2lhdGlvbnMKZGlzYXNzb2NfbG93X2Fjaz0wCmFwX21heF9pbmFjdGl2aXR5PTkwMDAwMDAKIyBza2lwX2luYWN0aXZpdHlfcG9sbD0xCmFwX2lzb2xhdGU9MAojZWFwb2xfdmVyc2lvbj0yCmFwX3RhYmxlX2V4cGlyYXRpb25fdGltZT0zNjAwMAoKIyBBbGd1bm9zIHZhbG9yZXMgc29wb3J0YWRvcyBwYXJhICdodF9jYXBhYicgcXVlIHB1ZWRlIHV0aWxpemFyIHBhcmEgc3UgdGFyamV0YToKIyBbTERQQ10gW0hUNDAtXSBbU01QUy1TVEFUSUNdIFtTTVBTLURZTkFNSUNdIFtHRl0gW1NIT1JULUdJLTIwXSBbU0hPUlQtR0ktNDBdW1RYLVNUQkNdW1JYLVNUQkMxXVtSWC1TVEJDMTJdIFtSWC1TVEJDMTIzXVtERUxBWUVELUJBXVtNQVgtQU1TRFUtNzkzNV0gW0RTU1NfQ0NLLTQwXSBbNDAtSU5UT0xFUkFOVF1bTFNJRy1UWE9QLVBST1RdCgo="

apsh="IyEvYmluL2Jhc2gKI0F1dG9yOiBAam9zZWNjbmV0CnRpbWVkYXRlPSQoZGF0ZSArJVklbSVkLSVIJU0lUykKCm1vZGVOZXQ9JDEKaWZhY2U9JDIKc3VibmV0PSQzCmFwTmFtZT0kNAphcFBhc3N3b3JkPSQ1CgplY2hvIC1lICItLS0gSW5pY2lhbmRvIEFQIGVuICRpZmFjZSAsICQoZGF0ZSkgLS0tIgoKI1NpbmNyb25pemFtb3MgbGEgZmVjaGEvaG9yYToKL3Vzci9zYmluL250cGRhdGUgdGltZTEuZ29vZ2xlLmNvbSA+IC9kZXYvbnVsbCAyPiYxIHx8IC91c3Ivc2Jpbi9udHBkYXRlIHRpbWUyLmdvb2dsZS5jb20gPiAvZGV2L251bGwgMj4mMSB8fCAvdXNyL3NiaW4vbnRwZGF0ZSB0aW1lMy5nb29nbGUuY29tID4gL2Rldi9udWxsIDI+JjEgfHwgL3Vzci9zYmluL250cGRhdGUgdGltZTQuZ29vZ2xlLmNvbSA+IC9kZXYvbnVsbCAyPiYxICYKCiMiQXl1ZGEiIGEgZXZpdGFyIGRlc2NvbmV4aW9uZXMgZW4gbG9zIGNsaWVudGVzKHNtYXJ0IHBob25lcywgdGFibGV0cywgLi4uKToKaWZjb25maWcgJGlmYWNlIGRvd24KaXdjb25maWcgJGlmYWNlIHR4cG93ZXIgYXV0bwppdyAkaWZhY2Ugc2V0IHBvd2VyX3NhdmUgb2ZmID4gL2Rldi9udWxsIDI+JjEgI0VudmlhIGVycm9yLCBob3N0YXBkIHNpIHRvbWEgZWwgY2FtYmlvLgojaXcgJGlmYWNlIGdldCBwb3dlcl9zYXZlCmlmY29uZmlnICRpZmFjZSB1cAoKZWNobyAxID4gL3Byb2Mvc3lzL25ldC9pcHY0L2NvbmYvJGlmYWNlL2FycF9maWx0ZXIKCmlmIFsgIiRtb2RlTmV0IiA9PSAiTW9kZU5BVCIgXSA7IHRoZW4KICAgZWNobyAtZSAiXG5ETlNNQVNROiAiCiAgIGtpbGwgLTkgJChwcyBhdXggfCBlZ3JlcCAiL3Vzci9zYmluL2Ruc21hc3EuKiRpZmFjZSIgfCBncmVwIC12IGdyZXAgfCBhd2sgJ3twcmludCAkMn0nKSA+IC9kZXYvbnVsbCAyPiYxICYmIHNsZWVwIDMKICAgL3Vzci9zYmluL2Ruc21hc3EgLS1uby1yZXNvbHYgLS1pbnRlcmZhY2U9JGlmYWNlIC0tZXhjZXB0LWludGVyZmFjZT1sbyAtLWJpbmQtaW50ZXJmYWNlcyAtLWRoY3AtcmFuZ2U9JHN1Ym5ldC41MCwkc3VibmV0LjI1MCw0OGggLXggL3Zhci9ydW4vZG5zbWFzcS0kaWZhY2UucGlkIC0tZGhjcC1vcHRpb249b3B0aW9uOnJvdXRlciwkc3VibmV0LjEgLS1kaGNwLW9wdGlvbj1vcHRpb246ZG5zLXNlcnZlciw4LjguOC44LDguOC40LjQgLS1kbnMtZm9yd2FyZC1tYXg9MTUwMAogICBlY2hvIC1uICJbJD9dIgogICBzZWQgLWUgInMvd2xhbk4vJGlmYWNlL2ciIC1lICJzL015T3duQVBSQU5ET00vJGFwTmFtZS9nIiAtZSAicy9wYXNzd29yZEFQLyRhcFBhc3N3b3JkL2ciIC1lICJzL2JyaWRnZT1icjAvI2JyaWRnZT1icjAvZyIgL29wdC9hcC9ob3N0YXBkLmNvbmYudGVtcGxhdGUgPiAvb3B0L2FwL2hvc3RhcGQtJGlmYWNlLmNvbmYKICAgcm1tb2QgYnJpZGdlID4gL2Rldi9udWxsIDI+JjEKZWxpZiBbICIkbW9kZU5ldCIgPT0gIk1vZGVCcmlkZ2UiIF0gOyB0aGVuCiAgIHNlZCAtZSAicy93bGFuTi8kaWZhY2UvZyIgLWUgInMvTXlPd25BUFJBTkRPTS8kYXBOYW1lL2ciIC1lICJzL3Bhc3N3b3JkQVAvJGFwUGFzc3dvcmQvZyIgL29wdC9hcC9ob3N0YXBkLmNvbmYudGVtcGxhdGUgPiAvb3B0L2FwL2hvc3RhcGQtJGlmYWNlLmNvbmYKZWxzZQogICBlY2hvICJFcnJvciwgY29uZmlndXJhY2lvbiBpbnZhbGlkYS4gUmV2aXNlIC9ldGMvbmV0d29yay9pbnRlcmZhY2VzIiA7IGV4aXQgLTEKZmkKaXdjb25maWcgMj4mMSB8IGdyZXAgJGlmYWNlIHwgZ3JlcCAnODAyLjExYmduJwppZiBbICIkPyIgPT0gIjAiIF0gOyB0aGVuCiAgIGVjaG8gLWUgIlxuaWVlZTgwMjExbj0xICMgODAyLjExbiBzdXBwb3J0XG53bW1fZW5hYmxlZD0xICMgUW9TIHN1cHBvcnRcbmh0X2NhcGFiPVtTSE9SVC1HSS00MF1bRFNTU19DQ0stNDBdXG4iID4+IC9vcHQvYXAvaG9zdGFwZC0kaWZhY2UuY29uZgpmaQoKZWNobyAtZSAiXG5IT1NUQVBEOiAiCmtpbGwgLTkgJChwcyBhdXggfCBlZ3JlcCAiL3Vzci9zYmluL2hvc3RhcGQuKiRpZmFjZSIgfCBncmVwIC12IGdyZXAgfCBhd2sgJ3twcmludCAkMn0nKSA+IC9kZXYvbnVsbCAyPiYxICYmIHNsZWVwIDYKL3Vzci9zYmluL2hvc3RhcGQgLUIgLWYgL3Zhci9sb2cvaG9zdGFwZC0kaWZhY2UubG9nIC9vcHQvYXAvaG9zdGFwZC0kaWZhY2UuY29uZgplY2hvIC1uICJbJD9dIgoKI0FzZWd1cmFtb3MgcmVtb3ZlciBlbCBkcml2ZXIgY3VhbmRvIHNlIGRlc2NvbmVjdGUgZWwgVVNCOgpjZCAvdG1wIDsgcm0gLWYgd2xhbi5kcml2ZXIuKiAyPi9kZXYvbnVsbApod2luZm8gLS13bGFuIDI+L2Rldi9udWxsIHwgZWdyZXAgLWkgIlZlbmRvcjp8RGV2aWNlOnxEcml2ZXI6IiB8IHNlZCAtZSAncy8gLy9nJyAtZSAncy8iLy9nJyB8IHNwbGl0IC1kIC1sIDMgLSB3bGFuLmRyaXZlci4KZm9yIGkgaW4gJCh3YyAtbCB3bGFuLmRyaXZlci4qIHwgZWdyZXAgIjMuKndsYW4uZHJpdmVyLiIgfCBhd2sgJ3twcmludCAkTkZ9JykKZG8KICAgdmVuZG9yPSQoZ3JlcCBWZW5kb3IgJGkgfCBncmVwIC1vUCAweFswLTlhLXpBLVpdWzAtOWEtekEtWl1bMC05YS16QS1aXVswLTlhLXpBLVpdIHwgc2VkICdzLzB4Ly9nJykKICAgZGV2aWNlPSQoZ3JlcCBEZXZpY2UgJGkgfCBncmVwIC1vUCAweFswLTlhLXpBLVpdWzAtOWEtekEtWl1bMC05YS16QS1aXVswLTlhLXpBLVpdIHwgc2VkICdzLzB4Ly9nJykKICAgZHJpdmVyPSQoZ3JlcCBEcml2ZXIgJGkgfCBhd2sgLUZcOiAne3ByaW50ICQyfScpCiAgIGVncmVwICJyZW1vdmUuKm5ldC4qJGRldmljZS4qJHZlbmRvci4qJGRyaXZlciIgL2V0Yy91ZGV2L3J1bGVzLmQvNzAtcGVyc2lzdGVudC1uZXQucnVsZXMgPiAvZGV2L251bGwgMj4mMQogICBpZiBbICIkPyIgIT0gIjAiIF0gJiYgWyAiJGRyaXZlciIgIT0gIiIgXSA7IHRoZW4KICAgICAgZWNobyAnQUNUSU9OPT0icmVtb3ZlIiwgU1VCU1lTVEVNPT0ibmV0IiwgRU5We0lEX01PREVMX0lEfT09Il9kZXZpY2UiLCBFTlZ7SURfVkVORE9SX0lEfT09Il92ZW5kb3IiLCBSVU4rPSIvc2Jpbi9ybW1vZCBfZHJpdmVyIicgfCBzZWQgLWUgInMvX2RldmljZS8kZGV2aWNlL2ciIC1lICJzL192ZW5kb3IvJHZlbmRvci9nIiAtZSAicy9fZHJpdmVyLyRkcml2ZXIvZyIgPj4gL2V0Yy91ZGV2L3J1bGVzLmQvNzAtcGVyc2lzdGVudC1uZXQucnVsZXMKICAgZmkKZG9uZQpjcCAtZiAvZXRjL3VkZXYvcnVsZXMuZC83MC1wZXJzaXN0ZW50LW5ldC5ydWxlcyAvZXRjL3VkZXYvcnVsZXMuZC83MC1wZXJzaXN0ZW50LW5ldC5ydWxlcy4kdGltZWRhdGUKYXdrICcheFskMF0rKycgL2V0Yy91ZGV2L3J1bGVzLmQvNzAtcGVyc2lzdGVudC1uZXQucnVsZXMuJHRpbWVkYXRlID4gL2V0Yy91ZGV2L3J1bGVzLmQvNzAtcGVyc2lzdGVudC1uZXQucnVsZXMKdWRldmFkbSBjb250cm9sIC0tcmVsb2FkLXJ1bGVzCgojaXcgd2xhbjAgZ2V0IHBvd2VyX3NhdmUgI1NvbG8gcGFyYSBoYWNlciBkZWJ1ZwoKZWNobyAtZSAiXG4tLS0gRG9uZSBBUCBlbiAkaWZhY2UgLCAkKGRhdGUpIC0tLSIKCmV4aXQgMAo="

grep -i wheezy /etc/os-release > /dev/null 2>&1
if [ "$?" == "0" ] ; then
	etcaptsourceslist=$etcaptsourceslistdeb7
	aptoptions="-t wheezy-backports"
else
	grep -i jessie /etc/os-release > /dev/null 2>&1
	if [ "$?" == "0" ] ; then
		etcaptsourceslist=$etcaptsourceslistdeb8
		aptoptions=""
	else
	    echo "Sistema Operativo no soportado"
	    exit -1
	fi
fi

cp /etc/apt/sources.list /etc/apt/sources.list.$timedate
echo $etcaptsourceslist | base64 --decode > /etc/apt/sources.list

apt-get -y update || exit -1
firmwarewireless=$(apt-cache $aptoptions search firmware- | grep -i wireless | awk '{print $1}')
aptpakages="hostapd rfkill dnsmasq iw bridge-utils ntpdate haveged hwinfo libpcre3"
apt-get $aptoptions -y install $aptpakages $firmwarewireless || exit -1
apt-get -y upgrade || exit -1
apt-get clean all

#Sincronizamos la fecha/hora:
/usr/sbin/ntpdate time1.google.com > /dev/null 2>&1 || /usr/sbin/ntpdate time2.google.com > /dev/null 2>&1 || /usr/sbin/ntpdate time3.google.com > /dev/null 2>&1 || /usr/sbin/ntpdate time4.google.com > /dev/null 2>&1 &

update-rc.d hostapd disable > /dev/null 2>&1
mv /etc/init.d/hostapd /etc/init.d/hostapd.nousar
update-rc.d dnsmasq disable > /dev/null 2>&1
mv /etc/init.d/dnsmasq /etc/init.d/dnsmasq.nousar

cp /etc/network/interfaces /etc/network/interfaces.original.$timedate
echo $etcnetworkinterfacesBridge | base64 --decode > /opt/ap/interfaces.Bridge
echo $etcnetworkinterfacesNAT | base64 --decode > /opt/ap/interfaces.Nat
echo $hostapdconftemplate | base64 --decode > /opt/ap/hostapd.conf.template
echo $apsh | base64 --decode > /opt/ap/ap.sh
chmod 750 /opt/ap/*.sh

cp /opt/ap/interfaces.Nat /etc/network/interfaces

echo -e "\n***********************"
echo "Instalacion de software lista!. Tome nota:"

echo "1) Reinicie el servidor virtual y cuando este arriba, conecte la(s) interfaz de red USB, en unos segundos podra utilizar el Access Point."

echo "2) El servidor virtual debe recibir la IP por medio de DHCP y debe tener salida a Internet."

echo "3) Inicialmente, el archivo /etc/network/interfaces es una copia de /opt/ap/interfaces.Nat. Tambien puede probar copiar el archivo /opt/ap/interfaces.Bridge a /etc/network/interfaces (y reiniciar el servidor)"

echo "4) El nombre del Access Point y la contraseña, puede obtenerla/cambiarla en el archivo /etc/network/interfaces. Por default AP-Name-wlanX / 1133557799"

echo "5) ++Disfrute++ su Access Point."

echo -e "***********************\n"

#https://wiki.gentoo.org/wiki/Hostapd
#wget https://github.com/khernyo/network-limiter/raw/master/slow/slow

exit 0
